import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

import {chekRegister} from "@/api/auth";
import SignInComponent from "@/components/signin/SignIn";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  if (await chekRegister()){
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header className="header"/>
          <main>{children}</main>
        <Footer className="footer"/>
      </body>
    </html>
  );
} else{
  return(
    <>
    <html lang="en">
      <body className={montserrat.className}>
        <Header className="header"/>
          <main><SignInComponent/></main>
        <Footer className="footer"/>
      </body>
    </html>
      
    </>
  )
}
}
